name = input("Enter your name: ")
age = int(input("Enter your Age: "))
city = input("Enter your City: ")
lang = input("Enter your Favorite Language: ")
print(f'Name: {name} \nAge: {age} \nCity: {city}\nFavorite Language: {lang}')